version: '3'
services:
  redis:
    image: redis
    container_name: meu-redis
    ports:
      - "6379:6379"
  postgresql:
    container_name: postgresql_container
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data